  version: '3.8'

  services:

    api:
      container_name: realestateapi_container
      image: realestateapi_image
      restart: always
      build: .
      ports:
        - "8080:8080"
      environment:
        MYSQL_HOST: database
        MYSQL_USER: munashe
        MYSQL_PASSWORD: stabnashiamunashe
        MYSQL_PORT: 3306

    database:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: stabnashiamunashe
        MYSQL_DATABASE: realestatedb
        MYSQL_USER: munashe
        MYSQL_PASSWORD: stabnashiamunashe
      volumes:
        - dbdata:/var/lib/mysql
      ports:
        - "3306:3306"

  volumes:
    dbdata:
